import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Github Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Github Stars</h1>
        <p className={styles.description}>Find out who starred your repo✨</p>
        <form className={styles.form}>
          <input 
            id="name" 
            name="name" 
            type="text" 
            placeholder="Enter github repository" 
            required/>
          <button>Submit</button>
        </form>
        <div className={styles.line}>
        </div>
        <div className={styles.grid}>
          <a href="https://github.com/sumana2001">
            <figure className={styles.card}>
              <div className={styles.image}>
                <img src="https://avatars.githubusercontent.com/u/63084088?v=4" alt="profile-img"/>
              </div>
              <figcaption>
                <div className={styles.star}>&#9733;</div>
                <h3>Sumana Basu</h3>
                <p>sumana2001</p>
              </figcaption>
            </figure>
          </a>

          <a href="https://github.com/sumana2001">
            <figure className={styles.card}>
              <div className={styles.image}>
                <img src="https://avatars.githubusercontent.com/u/63084088?v=4" alt="profile-img"/>
              </div>
              <figcaption>
                <div className={styles.star}>&#9733;</div>
                <h3>Sumana Basu</h3>
                <p>sumana2001</p>
              </figcaption>
            </figure>
          </a>

          <a href="https://github.com/sumana2001">
            <figure className={styles.card}>
              <div className={styles.image}>
                <img src="https://avatars.githubusercontent.com/u/63084088?v=4" alt="profile-img"/>
              </div>
              <figcaption>
                <div className={styles.star}>&#9733;</div>
                <h3>Sumana Basu</h3>
                <p>sumana2001</p>
              </figcaption>
            </figure>
          </a>

          <a href="https://github.com/sumana2001">
            <figure className={styles.card}>
              <div className={styles.image}>
                <img src="https://avatars.githubusercontent.com/u/63084088?v=4" alt="profile-img"/>
              </div>
              <figcaption>
                <div className={styles.star}>&#9733;</div>
                <h3>Sumana Basu</h3>
                <p>sumana2001</p>
              </figcaption>
            </figure>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>Made with &hearts;</footer>
    </div>
  )
}

export default Home
